import React, { Component } from 'react';
import './bootstrap.min.css';
import './style.css'
function Valuate(props) {
    
    var displayer= [["Valuation for M&A Transaction and Restructuring", "We believe 60 to 70 percent of all transactions do not achieve their upfront performance expectations due to ineffective transaction planning and implementation and post transaction business integration.  A transaction represents a significant event that requires careful management and significant time commitment to achieve expected benefits consistent with timeline expectations. In such cases valuation becomes more critical. We work to help the client derive the maximum benefit from a merger or acquisition transaction by assisting them in estimating the value through a defendable valuation process. We are highly experienced professionals with skills and experience doing the valuation for buying and selling closely-held businesses.We carryout valuations for the purpose of - Business purchase . Business sale, Purchase price allocations (PPA), M&A (Mergers & Acquisition), Reverse merger, Recapitalization, Restructuring, LBO (Leverage Buy Out), MBO (Management Buy Out), MBI (Management Buy In), BSA (Buy Sell Agreement), IPO, ESOPs, Buy back of shares, Project financing and others , Intangibles asset / Patent/ Copy right etc , Valuation of distressed asset sale and special purpose assets"], 
    ["Litigation and Settlement Valuation", "The conflicts associated with commercial, shareholder  and disputes can involve loss of business reputation, economic value, loss of profit, bankruptcy, stakeholder disagreements, minority shareholder oppression post-merger and acquisition disputes, not to mention loss of time and precious financial resources.   At Armslength, we help our clients to resolve such issues by providing expert and unbiased valuation opinions. Our in-depth study of data can help to determine fair valuations to allow for smooth and timely resolution of cases.    Our Litigation and Settlement valuation services includes valuation for the purpose of Commercial and Shareholder Disputes Insolvency & Bankruptcy Family Settlement and Partition Matrimonial disputes Settlement Our experts can also bear testimony as expert witness for the same in a court of law."], 
    ["Real Estate Valuation ", "Real estate valuations play a pivotal role in today’s business climate. A true and well supported opinion of property value can mean the difference between reaching a critical goal - securing a loan, closing a sale, reporting to investors, choosing the best asset - or failing to achieve it altogether. The real estate team at Armslength specializes in comprehensive valuation of real estate for investors, lenders, Funds and real estate owners. We carry out valuation of real property for sale/ purchase transactions, distribution among the family for a family settlement, for accounting, impairment testing etc."],
     ["Compliance Valuation", "Being in compliance is one of the most important aspects of today’s business environment. Today, a business faces a myriad of different compliance rules that they must adhere to. Valuation regulations have become a growing concern for all businesses, more importantly, after introduction of valuation regulations under the Companies Act, Income Tax Act, FEMA etc..The businesses must always be compliant  with valuation rules. If they are not, the result can be significant penalties and costly time spent on correcting the errors.At Armslength we carry out the following compliance related valuations, Valuation for Indirect Transfer under Section  9(1) (i) of Income Tac Act read with Rule 11UB,Valuation of issue of fresh under Section 56(2)(viib) of the Income Tax Act, 1961 read with Rule 11UA(2)(b),Determination of Arms’ Length Price for Transfer Pricing Compliance under Section 192 of Income Tax Act,Valuation for Foreign Exchange Management Act (FEMA) and Reserve Bank of India (RBI) regulations Compliances Valuation for the Companies Act Compliances, such as valuation for right issues u/s 68, conversion of debt into preference shares in compliance with Section 42 of the Companies Act, 2013, read with the Companies (Share Capital and Debentures), Rules, 2014, Non cash transactions with directors u/s 192(2), Purchase of minority shareholding u/s 236(2), Valuation in respect of shares and assets to arrive at the reserve price for company administration u/s 260(2)(1), Valuing assets for submission of report by company liquidator u/s 281(1)(a), Report on assets for declaration of solvency in case of proposal to wind up voluntarily u/s  305(2)(d), Valuation for Securities and Exchange Board of India (SEBI) compliances "],
      ["Financial Reporting Valuation", "The requirement of fair value measurement for financial reporting purposes has meant that the topic of valuations has moved up the agendas of standard setters, regulators and accounting professionals.In an environment of increasingly complex fair value reporting standards and increasing regulatory scrutiny, Armslength helps clients resolve financial reporting valuation issues successfully.With an hands on experience over a decade in handling engagements of fair valuation opinions in compliance with IFRS, US GAAP, FRS Singapore and Ind AS, the team at Armslength is well versed in providing practical and implementable solutions to its clients. Our financial reporting valuation services include: Purchase price allocation (“PPA”) per requirement of Ind AS 103/ IFRS 3/ASC 820/ ASC 805 Valuation of employee stock options and restricted stock awards per ASC 718/ Ind AS 102/ IFRS 2 Impairment analyses for goodwill, other intangibles and long-lived assets per ASC 350, ASC 360/ Ind AS 36/ IFRS 36 Valuation of intangibles like customer relationships, trademarks, technology, patents, databases, domain names, websites, brands, software etc.Valuation of financial instruments encompassing derivatives, structured products, foreign currency convertible bonds and preferred stock, guarantees and indemnifications"]];
    ;
    return (
        <div className="jumbotron">
            <div className="container-fluid">
                <hr class="my-4"></hr>
                <h1 className="display-8" id="about">Services</h1>
                <hr class="my-4"></hr>
                <h3 className="display-12" id="about">{displayer[props.val][0]}</h3>
                <p className="lead">{displayer[props.val][1]}</p>
           
            </div>
        </div>

    );


    
}

export default Valuate;